FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# TODO enter your organization's name below
LABEL MAINTAINER=""

RUN python3 -m pip install \
    pyyaml \
    ics \
    requests \
    html2text \
    markdown

COPY ./app /app
