apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    
    - rolearn: arn:aws:iam::us-west-2:role/osl-cluster-hub-instance
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    
    - rolearn: arn:aws:iam::us-west-2:role/osl-cluster-sar_1-instance
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    
    - rolearn: arn:aws:iam::us-west-2:role/osl-cluster-sar_2-instance
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    
    - rolearn: arn:aws:iam::us-west-2:role/osl-cluster-gpu-instance
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    
    - rolearn: USER_ACCESS_ROLE_ARN
      username: user-access-role
      groups:
        - system:masters