# !!!! This config is used in the first round of Franz's labs. It will not be used afterwards. Though some of the settings could still prove useful.
#
# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

auth:
  admin:
    users:
    - ADMIN_USER

  whitelist:
    users:
    - ADMIN_USER

prePuller:
  continuous:
    enabled: true
  hook:
    enabled: true

proxy:
  https:
    enabled: false
  secretToken: SECRET_TOKEN
  service:
    nodePorts:
      http: NODE_PORT
    type: NodePort

singleuser:
  extraEnv:
    AWS_ACCESS_KEY_ID: NODE_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: NODE_SECRET_KEY
  image:
    name: IMAGE_NAME
    tag: IMAGE_TAG
  lifecycleHooks:
    postStart:
      exec:
        command:
        - gitpuller
        - https://github.com/asfadmin/asf-jupyter-notebooks.git
        - master
        - notebooks
  storage:
    capacity: 100Gi

hub:
  extraConfig:
    myAuthConfig.py: |
       # The try/except is needed since the hub needs to be created before earthdata.py is copied over to /svc/jupyterhub/
       # After copying, the hub will need to be forced to rebuild. However, the earthdata file will persist.
       # The try/expect can be removed after the earthdata module is formally integrated into the official oauthenticator module repo.
       try:
         # The following three lines are a hack to make things work and will not be needed in the final product
         import sys
         sys.path.append("/srv/jupyterhub")
         from earthdata import EarthdataOAuthenticator

         # Uncomment this line after merging earthdata.py into the oauthenticator module
         #from oauthenticator.earthdata import EarthdataOAuthenticator
         import z2jh
         c.JupyterHub.authenticator_class = EarthdataOAuthenticator
         c.EarthdataOAuthenticator.oauth_callback_url = '{0}/hub/oauth_callback'.format(z2jh.get_config("custom.OAUTH_DNS_NAME"))
         c.EarthdataOAuthenticator.client_id = '{0}'.format(z2jh.get_config("custom.OAUTH_CLIENT_ID"))
         c.EarthdataOAuthenticator.client_secret = '{0}'.format(z2jh.get_config("custom.OAUTH_CLIENT_SECRET"))
         c.EarthdataOAuthenticator.login_service = 'Earthdata Login'
       except Exception as e:
         print(e)

custom:
  OAUTH_DNS_NAME: OAUTH_DNS_NAME
  OAUTH_CLIENT_ID: OAUTH_CLIENT_ID
  OAUTH_CLIENT_SECRET: OAUTH_CLIENT_SECRET
