# !!!! This config is used in the first round of Franz's labs. It will not be used afterwards. Though some of the settings could still prove useful.
#
# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

proxy:
  https:
    enabled: false
  secretToken: SECRET_TOKEN
  service:
    nodePorts:
      http: NODE_PORT
    type: NodePort

singleuser:
  startTimeout: 600
  storage:
    dynamic:
      storageClass: gp2
      pvcNameTemplate: claim-{username}

prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false

cull:
  enabled: true
  timeout: 3600
  every: 300

scheduling:
  userPlaceholder:
    enabled: false
  userScheduler:
    enabled: true
  corePods:
    nodeAffinity:
      matchNodePurpose: require  # hub.jupyter.org/node-purpose=core
  userPods:
    nodeAffinity:
      matchNodePurpose: require  # hub.jupyter.org/node-purpose=user

custom:
  OAUTH_JUPYTER_URL: OAUTH_JUPYTER_URL
  OAUTH_DNS_NAME: OAUTH_DNS_NAME
  OAUTH_POOL_NAME: OAUTH_POOL_NAME
  CLUSTER_NAME: CLUSTER_NAME
  COST_TAG_VALUE: COST_TAG_VALUE
  AZ_NAME: AZ_NAME
  IMAGE_REPO_URL: IMAGE_REPO_URL

hub:
    config:
      JupyterHub:
        admin_access: true
      Authenticator:
        admin_users:
         - ADMIN_USER

    image:
      imagePullPolicy: Always
      name: HUB_IMAGE_NAME_HERE
      tag: latest

    extraConfig:
        myAuthConfig.py: |
            try:
                import os
                import z2jh

                os.environ["OAUTH_DNS_NAME"] = z2jh.get_config("custom.OAUTH_DNS_NAME")
                os.environ["OAUTH_JUPYTER_URL"] = z2jh.get_config("custom.OAUTH_JUPYTER_URL")
                os.environ['OAUTH_POOL_NAME'] = z2jh.get_config("custom.OAUTH_POOL_NAME")
                os.environ['REGION_NAME'] = z2jh.get_config('custom.AZ_NAME')[:-1]

                from generic_with_logout import GenericOAuthenticator
                c.JupyterHub.authenticator_class = GenericOAuthenticator

            except Exception as e:
                print(e)

        myHooks.py: |
            import z2jh

            # Before mounting the home directory, check to see if a volume exists.
            # If it doesn't, check for any EBS snapshots.
            # If a snapshot exists, create a volume from the snapshot.
            # Otherwise, JupyterHub will do the mounting and other volume handling.
            def my_pre_hook(spawner):
                try:
                    from volume_from_snapshot import volume_from_snapshot

                    meta = {
                        'username': spawner.user.name,
                        'pvc_name': spawner.pvc_name,
                        'namespace': 'jupyter',
                        'cluster_name': z2jh.get_config('custom.CLUSTER_NAME'),
                        'cost_tag_value': z2jh.get_config('custom.COST_TAG_VALUE'),
                        'az_name': z2jh.get_config('custom.AZ_NAME'),
                        'vol_size': spawner.storage_capacity,
                        'spawn_pvc': spawner.get_pvc_manifest()
                    }

                    volume_from_snapshot(meta)

                except Exception as e:
                    print(e)
                    raise

            c.Spawner.pre_spawn_hook = my_pre_hook


            # After stopping the notebook server, tag the volume with the current "stopping" time. This will help determine which volumes are active.
            def my_post_hook(spawner):
                try:
                    from volume_stopping_tags import volume_stopping_tags

                    meta = {
                        'pvc_name': spawner.pvc_name,
                        'cluster_name': z2jh.get_config('custom.CLUSTER_NAME'),
                        'az_name': z2jh.get_config('custom.AZ_NAME')
                    }

                    volume_stopping_tags(meta)

                except Exception as e:
                    print("Something went wrong with the volume stopping tag post hook...")
                    print(e)
                    raise

            c.Spawner.post_stop_hook = my_post_hook

        myHubCron.py: |
            import os
            import z2jh
            try:
                from crontab import CronTab

                days_vol_inactive_till_termination = 5

                # Set metadata for use by cron scripts
                meta = [
                    "---",
                    "days_vol_inactive_till_termination: {days_vol_inactive_till_termination}",
                    "namespace: jupyter",
                    "cluster_name: {cluster_name}",
                    "cognito_name: {cognito_name}",
                    "region_name: {region_name}",
                    "kubernetes_service_port: '{kubernetes_service_port}'",
                    "kubernetes_service_host: {kubernetes_service_host}"
                ]
                meta = "\n".join(meta).format(
                    days_vol_inactive_till_termination=days_vol_inactive_till_termination,
                    region_name=z2jh.get_config('custom.AZ_NAME')[:-1],
                    cluster_name=z2jh.get_config('custom.CLUSTER_NAME'),
                    cognito_name=z2jh.get_config('custom.OAUTH_POOL_NAME'),
                    kubernetes_service_port=os.environ['KUBERNETES_SERVICE_PORT'],
                    kubernetes_service_host=os.environ['KUBERNETES_SERVICE_HOST']
                )
                with open("/etc/jupyterhub/custom/meta.yaml", mode='w') as f:
                    f.write(meta)

                # Make file executable
                os.chmod('/etc/jupyterhub/custom/meta.yaml', 0o755)

                # Setup crontab for volume killer
                cron = CronTab(user='jovyan')

                # Lifecycle snapshot runs at 10 UTC, 1am AKST

                # Setup crontab for volume killer
                job2 = cron.new(command='python3 /etc/jupyterhub/custom/delete_volumes.py > /proc/1/fd/1 2>&1')
                job2.hour.on(12)  # 12 UTC, 3am AKST
                job2.minute.on(0)
                job2.enable()

                # Setup crontab for snapshot killer
                job3 = cron.new(command='python3 /etc/jupyterhub/custom/delete_snapshot.py > /proc/1/fd/1 2>&1')
                job3.hour.on(13)  # 13 UTC, 4am AKST
                job3.minute.on(0)
                job3.enable()

                cron.write()

            except Exception as e:
                print(e)

        myProfiles.py: |

            from typing import List, Dict

            import z2jh

            # Profile list programmatically
            # Ideally, if/else statements based on permissions would determine the final choices.
            # https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner
            # Other singleuser server params can be taken from above to below as needed.

            """
            To manually add some Groups and names to Groups, `kubectl` into the hub, python3 and

            from jupyterhub import groups

            g = groups.Groups()
            g.add_group('general_cpu')
            g.get_users_in_group('general_cpu')
            g.add_user_to_group('emlundell_test1', 'general_cpu')
            g.get_users_in_group('general_cpu')


            The `server_type` found in the profiles (e.g. general_cpu_large) are defined in the cloudformation template.
            """

            class NoProfileException(Exception):
                """No Profiles found"""

            def profile_list_hook(spawner: c.Spawner) -> List[Dict]:

                try:
                    from jupyterhub import groups as groups_py

                    user_name = spawner.user.name

                    groups = groups_py.Groups()
                    group_list = groups.get_all_enabled_group_names_for_user(user_name=user_name)
                    group_list.extend(groups.get_all_enabled_group_names_set_to_all_users())
                    
                    if not group_list:
                        raise NoProfileException()

                    print(f"Group list: {group_list}")

                    profile_list = []

                    # m5a.2xlarge: 8 cpus, 32 GiB RAM
                    if 'SAR_1_-_Test' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar:49320d9"
                        profile = {
                            'display_name': 'SAR 1 - Test',
                            'description': 'Formerly the General CPU option. Contains basic SAR processing packages: ARIA, ISCE, MintPy, MapReady, TRAIN. CPU limit: 8. RAM limit: 16G. Storage: 500G.',
                            'default': True,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_1'
                                },
                                'node_selector': {
                                    'server_type': 'sar_1'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/sar_test.sh"]
                                        }
                                    }
                                },
                                'mem_limit': '16G', 
                                'mem_guarantee': '6G',
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)

                    # m5a.2xlarge: 8 cpus, 32 GiB RAM
                    if 'SAR_1' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar_old:old"
                        profile = {
                            'display_name': 'SAR 1',
                            'description': 'Formerly the General CPU option. Contains basic SAR processing packages: ARIA, ISCE, MintPy, MapReady, TRAIN. CPU limit: 8. RAM limit: 16G. Storage: 500G.',
                            'default': True,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_1'
                                },
                                'node_selector': {
                                    'server_type': 'sar_1'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/general_cpu.sh"]
                                        }
                                    }
                                },
                                'mem_limit': '16G', 
                                'mem_guarantee': '6G',
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)

                    # m5a.2xlarge: 8 cpus, 32 GiB RAM
                    if 'SAR_1_-_Dev' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar:49320d9"
                        profile = {
                            'display_name': 'SAR 1 - Dev',
                            'description': 'Development profile. CPU limit: 8. RAM limit: 16G. Storage: 500G.',
                            'default': False,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_1'
                                },
                                'node_selector': {
                                    'server_type': 'sar_1'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/sar_dev.sh"]
                                        }
                                    }
                                },
                                'mem_limit': '16G', 
                                'mem_guarantee': '6G',
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)
                    
                    # m5a.8xlarge: 32 cpu, 128 GiB RAM
                    if 'SAR_2' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar_old:old"
                        profile = {
                            'display_name': 'SAR 2',
                            'description': 'Formally UNAVCO. Contains basic SAR processing packages on a bigger machine. RAM limit: 96G. CPU limit: 8 cpus. Storage: 500 GiB.',
                            'default': False,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_2'
                                },
                                'node_selector': {
                                    'server_type': 'sar_2'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/unavco.sh"]
                                        }
                                    }
                                },
                                'mem_limit': '96G', 
                                'mem_guarantee': '32G', 
                                'cpu_limit': 8,
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)

                    # m5a.8xlarge: 32 cpu, 128 GiB RAM
                    if 'SAR_2_-_Max' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar_old:old"
                        profile = {
                            'display_name': 'SAR 2 - Max',
                            'description': 'Similar to SAR 2 but one person per machine. RAM limit: ~128GB. CPU limit: ~30 cpus. Storage: 500 GiB.',
                            'default': False,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_2'
                                },
                                'node_selector': {
                                    'server_type': 'sar_2'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/unavco.sh"]
                                        }
                                    }
                                },
                                'cpu_guarantee': 30,
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)

                    if 'SAR_1_-_No_Gitpuller' in group_list:
                        image_url = f"{z2jh.get_config('custom.IMAGE_REPO_URL')}/sar_old:old"
                        profile = {
                            'display_name': 'SAR 1 - No Gitpuller',
                            'description': 'Useful for debugging some server timeouts. This does not pull in the latest notebooks.',
                            'default': False,
                            'kubespawner_override': {
                                'extra_labels': {
                                    'server_type': 'sar_1',
                                    'extra_configs': 'no_smart_git'
                                },
                                'node_selector': {
                                    'server_type': 'sar_1'
                                },
                                'image': image_url,
                                'lifecycle_hooks': {
                                    "postStart": {
                                        "exec": {
                                            "command": ["/bin/sh", "-c", "/etc/jupyter-hooks/no_smart_git.sh"]
                                        }
                                    }
                                },
                                'mem_limit': '16G', 
                                'mem_guarantee': '6G', 
                                'cpu_guarantee': 1.25,
                                'storage_capacity': '500Gi'
                            }
                        }
                        profile_list.append(profile)

                    # This clause for sudo should always be last
                    if 'sudo' in group_list:
                        print("Adding sudo privs...")
                        spawner.args.append('--allow-root')
                        spawner.environment["GRANT_SUDO"] = "yes"
                        spawner.gid = 599

                        # Users should know that sudo is enabled in profile before entering
                        for profile in profile_list:
                            profile['display_name'] += " (Sudo Enabled)"
                    else:
                        print("Sudo privs not given.")

                    return profile_list 

                except NoProfileException as e:
                    print(f"No profiles found for user {spawner.user.name}.")
                    print(e)

                    return []

                except Exception as e:            
                    print("Something went wrong with the profiles list...")
                    print(e)

                    return []

            c.KubeSpawner.profile_list = profile_list_hook
