
nodes:
  - node_name: sar_1
    node_type: m5a.2xlarge

  - node_name: sar_2
    node_type: m5a.8xlarge

  - node_name: gpu
    node_type: whatever
    gpu: True

profiles:
  - name: Required Only
    description: "Formerly the General CPU option. Contains basic SAR processing packages: ARIA, ISCE, MintPy, MapReady, TRAIN. CPU limit: 8. RAM limit: 16G. Storage: 500G."
    image_name: sar
    image_tag: e914cd7
    node_name: sar_1
    storage_capacity: 500Gi
    ewewewe: wewew
    
  - name: SAR 1
    description: "Formerly the General CPU option. Contains basic SAR processing packages: ARIA, ISCE, MintPy, MapReady, TRAIN. CPU limit: 8. RAM limit: 16G. Storage: 500G."
    image_name: sar
    image_tag: e914cd7
    hook_script: sar.sh
    memory_guarantee: 6G
    memory_limit: 16G
    cpu_guarantee: None
    cpu_limit: None
    storage_capacity: 500Gi
    node_name: sar_1
    delete_user_volumes: False

  - name: SAR 1 - Test
    description: "Formerly the General CPU option. Contains basic SAR processing packages: ARIA, ISCE, MintPy, MapReady, TRAIN. CPU limit: 8. RAM limit: 16G. Storage: 500G."
    image_name: sar
    image_tag: e914cd7
    hook_script: sar_test.sh
    memory_guarantee: 6G
    memory_limit: 16G
    storage_capacity: 500Gi
    node_name: sar_1

  - name: SAR 1 - Dev
    description: "Development profile. CPU limit: 8. RAM limit: 16G. Storage: 500G"
    image_name: sar
    image_tag: e914cd7
    hook_script: sar_dev.sh
    memory_guarantee: 6G
    memory_limit: 16G
    storage_capacity: 500Gi
    node_name: sar_1

  - name: SAR 2
    description: "Formally UNAVCO. Contains basic SAR processing packages on a bigger machine. RAM limit: 96G. CPU limit: 8 cpus. Storage: 500 GiB."
    image_name: sar
    image_tag: e914cd7
    hook_script: sar.sh
    memory_guarantee: 32G
    memory_limit: 96G
    cpu_limit: 8
    storage_capacity: 500Gi
    node_name: sar_2

  - name: SAR 2 - Max
    description: "Similar to SAR 2 but one person per machine. RAM limit: ~128GB. CPU limit: ~30 cpus. Storage: 500 GiB."
    image_name: sar
    image_tag: e914cd7
    hook_script: sar.sh
    cpu_guarantee: 30
    storage_capacity: 500Gi
    node_name: sar_2
    delete_user_volumes: None
