apiVersion: v1
kind: Service
metadata:
  name: crons
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: crons
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
