dependencies:
  - name: jupyterhub
    version: 0.8.2
    repository: https://jupyterhub.github.io/helm-chart/
  - name: aws-cluster-autoscaler
    alias: autoscaler
    version: 0.3.3
    repository: https://storage.cloud.google.com/kubernetes-charts/
    
