FROM public.ecr.aws/docker/library/python:3.10

RUN apt update && \
    apt install -y python3-pip && \
    python3 -m pip install \
        boto3 \
        requests \
        kubernetes \
        opensarlab-backend==1.0.4 \
        escapism

COPY ./app /app
