
BasicLifecycleRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${AWS::Region}-${AWS::StackName}-SnapshotPolicyRole
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: dlm.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRole

BasicLifecyclePolicy:
  Type: "AWS::DLM::LifecyclePolicy"
  Properties:
    Description: !Sub "Lifecycle Policy for ${Cluster}"
    State: "ENABLED"
    ExecutionRoleArn: !GetAtt BasicLifecycleRole.Arn
    PolicyDetails:
      ResourceTypes:
        - "VOLUME"
      TargetTags:
        - Key: !Sub "kubernetes.io/cluster/${Cluster}"
          Value: "owned"
      Schedules:
        - Name: "Daily Snapshots"
          CreateRule:
            Interval: 24
            IntervalUnit: "HOURS"
            Times:
              - "10:00"
          RetainRule:
            Count: 1
          CopyTags: true
