# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

# Proxy token can be recreated via `openssl rand -hex 32`. This token isn't really used anywhere else so I'm not sure of the security concerns.
proxy:
  secretToken: fc097874c87cc7af8aa0fd47bf7a05baf937a3fdd9afc8d7e48242eaba4a8952

auth:
  admin:
    users:
      - emlundell
      - khogenso
  whitelist:
    users:
      - emlundell
      - khogenso
      - s1
      - s2
      - s3
      - s4
      - s5
      - s6
      - s7
      - s8
      - s9
      - s10
      - s11
      - s12
      - s13
      - s14
      - s15
      - s16
      - s17
      - s18
      - s19
      - s20
      - s21
      - s22
      - s23
  #dummy:
  #  password: "1111Q"

singleuser:
  image:
    name: 553778890976.dkr.ecr.us-east-1.amazonaws.com/asf-franz-labs
    tag: base

prepuller:
  continuous:
    enabled: false
  hook:
     enabled: false
