# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

# Proxy token can be recreated via `openssl rand -hex 32`. This token isn't really used anywhere else so I'm not sure of the security concerns.
proxy:
  secretToken: fc097874c87cc7af8aa0fd47bf7a05baf937a3fdd9afc8d7e48242eaba4a8952

auth:
  admin:
    users:
      - emlundell
      - khogenso
  whitelist:
    users:
      - emlundell
      - khogenso
      - s1
      - s2
      - s3
      - s4
      - s5
      - s6
      - s7
      - s8
      - s9
      - s10
      - s11
      - s12
      - s13
      - s14
      - s15
      - s16
      - s17
      - s18
      - s19
      - s20
      - s21
      - s22
      - s23
  #dummy:
  #  password: "1111Q"

  #type: custom
  #custom:
  #  className: oauthenticator.generic.GenericOAuthenticator
  #  config:
  #    login_service: "Earthdata URS"
  #    client_id: "BO_n7nTIlMljdvU6kRRB3g"
  #    client_secret: "Ech0.Ingest.Re5$t"
      #token_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
      #userdata_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
      #userdata_method: GET
      #userdata_params: {'state': 'state'}
      #username_key: preferred_username

singleuser:
  # Defines the default image
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  #profileList:
  #  - display_name: "Minimal environment"
  #    description: "To avoid too much bells and whistles: Python."
  #    default: true
  #  - display_name: "Datascience environment"
  #    description: "If you want the additional bells and whistles: Python, R, and Julia."
  #    kubespawner_override:
  #      image: jupyter/datascience-notebook:2343e33dec46
  #  - display_name: "Spark environment"
  #    description: "The Jupyter Stacks spark image!"
  #    kubespawner_override:
  #      image: jupyter/all-spark-notebook:2343e33dec46
