# !!!! This config is used in the first round of Franz's labs. It will not be used afterwards. Though some of the settings could still prove useful.
#
# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

proxy:
  https:
    enabled: false
  service:
    nodePorts:
      http: NODE_PORT
    type: NodePort

singleuser:
  startTimeout: 600
  storage:
    dynamic:
      storageClass: gp2
      pvcNameTemplate: claim-{username}

prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false

cull:
  enabled: true
  timeout: 3600
  every: 300

scheduling:
  userPlaceholder:
    enabled: false
  userScheduler:
    enabled: true
  corePods:
    nodeAffinity:
      matchNodePurpose: require  # hub.jupyter.org/node-purpose=core
  userPods:
    nodeAffinity:
      matchNodePurpose: require  # hub.jupyter.org/node-purpose=user

custom:
  OAUTH_JUPYTER_URL: OAUTH_JUPYTER_URL
  OAUTH_DNS_NAME: OAUTH_DNS_NAME
  OAUTH_POOL_NAME: OAUTH_POOL_NAME
  CLUSTER_NAME: CLUSTER_NAME
  COST_TAG_KEY: COST_TAG_KEY
  COST_TAG_VALUE: COST_TAG_VALUE
  AZ_NAME: AZ_NAME
  IMAGE_REPO_URL: IMAGE_REPO_URL

hub:
    config:
      JupyterHub:
        admin_access: true
      Authenticator:
        admin_users:
         - ADMIN_USER

    image:
      pullPolicy: Always
      name: HUB_IMAGE_NAME_HERE
      tag: HUB_IMAGE_TAG_HERE

    extraFiles:
      crons:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/crons.py
      crons_delete_snapshot:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/crons/delete_snapshots.py
      crons_delete_volumes:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/crons/delete_volumes.py
      hooks:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/hooks.py
      hooks_pv:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/hooks/pv.yaml
      hooks_pvc:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/hooks/pvc.yaml
      hooks_volume_from_snapshot:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/hooks/volume_from_snapshot.py
      hooks_volume_stopping_tags:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/hooks/volume_stopping_tags.py
      profiles:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/profiles.py
      services:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/services.py

    extraConfig:
      auth.py: |
        # Auth has to be put in extraConfig. If it is in extraFiles, JupyterHub will overwrite with the default dummy auth.
        import os
        import z2jh

        try:
            os.environ["OAUTH_DNS_NAME"] = z2jh.get_config("custom.OAUTH_DNS_NAME")
            os.environ["OAUTH_JUPYTER_URL"] = z2jh.get_config("custom.OAUTH_JUPYTER_URL")
            os.environ['OAUTH_POOL_NAME'] = z2jh.get_config("custom.OAUTH_POOL_NAME")
            os.environ['REGION_NAME'] = z2jh.get_config('custom.AZ_NAME')[:-1]

            from generic_with_logout import GenericOAuthenticator
            c.JupyterHub.authenticator_class = GenericOAuthenticator

        except Exception as e:
            print(e)