FROM jupyterhub/k8s-hub:JUPYTERHUB_HUB_IMAGE_VERSION_PLACEHOLDER as release

# By default, the notebook base image is set to non-sudo user joyvan. This makes root-ful actions difficult.
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install --no-install-recommends -y \
    tzdata
RUN ln -fs /usr/share/zoneinfo/America/Alaska /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt install --no-install-recommends -y \
    python3 \
    python3-pip \
    less \
    vim \
    patch

RUN python3 --version
RUN python3 -m pip install --upgrade \
        awscli \
        pyyaml \
        boto3 \
        kubernetes \
        kubernetes_asyncio \
        opensarlab-backend==1.0.4 \
        #jupyterhub-kubespawner==4.3.0 \
        --

COPY ./config.d/ /usr/local/etc/jupyterhub/jupyterhub_config.d/
COPY ./hub/web/usr/local/lib/jupyterhub/portal_auth.py /usr/local/lib/python3.9/site-packages/jupyterhub/portal_auth.py
COPY ./hub/web/usr/local/lib/jupyterhub/handlers/*.py /usr/local/lib/python3.9/site-packages/jupyterhub/handlers/
COPY ./hub/web/usr/local/share/jupyterhub/templates/custom/ /usr/local/share/jupyterhub/templates/custom/

ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/osl

RUN mkdir -p -m 775 /usr/local/secrets && chown 1000:root /usr/local/secrets

#RUN chmod 0755 /usr/local/etc/jupyterhub/jupyterhub_config.d/etc/pv.yaml 
#RUN chmod 0755 /usr/local/etc/jupyterhub/jupyterhub_config.d/etc/pvc.yaml
#RUN chmod 0777 /usr/local/lib/python3.9/site-packages/jupyterhub/portal_auth.py

USER jovyan 


FROM release as testing
