# !!!! This config is used in the first round of Franz's labs. It will not be used afterwards. Though some of the settings could still prove useful.
#
# This helm config file modifies the defaults found in zero-to-jupyterhub-k8s/jupyterhub/
# Possible values are scattered throughout the doc starting at https://z2jh.jupyter.org/en/latest/setup-jupyterhub.html

proxy:
  https:
    enabled: false
  service:
    nodePorts:
      http: NODE_PORT
    type: NodePort

singleuser:
  startTimeout: 600
  storage:
    dynamic:
      storageClass: gp2
      pvcNameTemplate: claim-{username}
  defaultUrl: "/lab"
  extraFiles:
    user-hooks-sar:
      mountPath: /etc/jupyter-hooks/sar.sh
      mode: 0755
    user-hooks-mapready:
      mountPath: /etc/jupyter-hooks/mapready.sh
      mode: 0755
    user-hooks-mapready-no-git:
      mountPath: /etc/jupyter-hooks/mapready_no_git.sh
      mode: 0755
    user-hooks-servir:
      mountPath: /etc/jupyter-hooks/servir.sh
      mode: 0755
    user-hooks-sar_test:
      mountPath: /etc/jupyter-hooks/sar_test.sh
      mode: 0755
    user-hooks-no_smart_git:
      mountPath: /etc/jupyter-hooks/no_smart_git.sh
      mode: 0755
    user-hooks-pull:
      mountPath: /etc/jupyter-hooks/scripts/pull.py
    user-hooks-clean:
      mountPath: /etc/jupyter-hooks/scripts/pkg_clean.py
    user-hooks-kernel-flag:
      mountPath: /etc/jupyter-hooks/etc/old_kernels_flag.txt
    user-hooks-kernel-flag-readme:
      mountPath: /etc/jupyter-hooks/etc/kernels_rename_README
    user-others-check_storage:
      mountPath: /etc/jupyter-hooks/resource_checks/check_storage.py
    user-custom_magics:
      mountPath: /etc/jupyter-hooks/custom_magics/00-df.py
    user-template-page:
      mountPath: /etc/jupyter-hooks/templates/page.html
      mode: 0755
    user-template-tree:
      mountPath: /etc/jupyter-hooks/templates/tree.html
      mode: 0755

prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false

#cull:
#  enabled: true
#  timeout: 3600
#  every: 300

scheduling:
  userPlaceholder:
    enabled: false
  userScheduler:
    enabled: true
  corePods:
    nodeAffinity:
      matchNodePurpose: require # hub.jupyter.org/node-purpose=core
  userPods:
    nodeAffinity:
      matchNodePurpose: require # hub.jupyter.org/node-purpose=user

custom:
  CLUSTER_NAME: CLUSTER_NAME
  COST_TAG_KEY: COST_TAG_KEY
  COST_TAG_VALUE: COST_TAG_VALUE
  AZ_NAME: AZ_NAME
  AWS_REGION: AWS_REGION
  REGISTRY_URI: REGISTRY_URI
  DAYS_TILL_VOLUME_DELETION: DAYS_TILL_VOLUME_DELETION
  DAYS_TILL_SNAPSHOT_DELETION: DAYS_TILL_SNAPSHOT_DELETION

hub:
  baseUrl: /lab/JUPYTERHUB_LAB_NAME_PLACEHOLDER/
  config:
    JupyterHub:
      admin_access: true
    Authenticator:
      admin_users:
        - ADMIN_USER
  extraEnv:
    JUPYTERHUB_LAB_NAME: JUPYTERHUB_LAB_NAME_PLACEHOLDER
    OPENSCIENCELAB_PORTAL_DOMAIN: OPENSCIENCELAB_PORTAL_DOMAIN_PLACEHOLDER
    OPENSARLAB_SSO_TOKEN_PATH: /usr/local/etc/jupyterhub/existing-secret/sso_token
  image:
    pullPolicy: Always
    name: HUB_IMAGE_NAME_PLACEHOLDER
    tag: HUB_IMAGE_TAG_PLACEHOLDER

  extraConfig:
    customTemplates.py: |
      c.JupyterHub.template_paths = ["/usr/local/share/jupyterhub/templates/custom/"]
