FROM jupyterhub/k8s-hub:0.9.0-beta.4
LABEL MAINTAINER="Alaska Satellite Facility"

# By default, the notebook base image is set to non-sudo user joyvan. This makes root-ful actions difficult.
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install --no-install-recommends -y \
    tzdata
RUN ln -fs /usr/share/zoneinfo/America/Alaska /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt install --no-install-recommends -y \
    python3 \
    python3-pip \
    python3-boto3 \
    cron \
    less \
    vim \
    sudo
RUN pip3 install --upgrade awscli pyyaml python-crontab

COPY alaska_satellite_facility_1000.png /usr/local/share/jupyterhub/static/images/alaska_satellite_facility_1000.png
COPY generic_with_logout.py /usr/local/lib/python3.6/dist-packages/generic_with_logout.py
COPY login.html /usr/local/share/jupyterhub/templates/login.html
COPY pending.html /usr/local/share/jupyterhub/templates/pending.html

RUN mkdir -p /etc/jupyterhub/custom
COPY pv.yaml /etc/jupyterhub/custom/pv.yaml
COPY pvc.yaml /etc/jupyterhub/custom/pvc.yaml
COPY volume_stopping_tags.py /etc/jupyterhub/custom/volume_stopping_tags.py
COPY volume_from_snapshot.py /etc/jupyterhub/custom/volume_from_snapshot.py
COPY delete_volumes.py /etc/jupyterhub/custom/delete_volumes.py
COPY delete_snapshot.py /etc/jupyterhub/custom/delete_snapshot.py
RUN chown -R 1000:0 /etc/jupyterhub/custom/
ENV PYTHONPATH "${PYTHONPATH}:/etc/jupyterhub/custom/"

RUN echo 'jovyan  ALL=NOPASSWD: /usr/sbin/service cron start' >> /etc/sudoers

USER jovyan
